use_frameworks!

target 'CrowdinSDK_Example' do
  pod 'CrowdinSDK', :path => '../'
  pod 'CrowdinSDK/FirebaseProvider', :path => '../'
  pod 'SwiftLint'
  pod 'FileBrowser', :git => 'https://github.com/serhii-londar/FileBrowser.git'
  pod 'Firebase'
  pod 'FirebaseDatabase'
  pod 'FAPanels'
  pod 'R.swift'
  pod 'DateToolsSwift'
  target 'CrowdinSDK_Tests' do
    inherit! :search_paths
  end
end
