# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppleReminders' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift', '4.3.1'
  pod 'SwiftDate'
  
  # Pods for AppleReminders

  target 'AppleRemindersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppleRemindersUITests' do
    # Pods for testing
  end

end
