# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'AppleReminders' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  pod 'SwiftDate'
#  pod 'DebugSwift', :configurations => ['Debug']
  
  pod 'CrowdinSDK', :path => '../'
  pod 'CrowdinSDK/Settings', :path => '../'
end

target 'AppleRemindersUITests' do
  pod 'CrowdinSDK/CrowdinXCTestScreenshots', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('12.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
