#!/bin/bash

# Sync version from Podspec to Swift code
./sync_pod_version.sh
if [ $? -ne 0 ]; then
    echo "Error syncing version."
    exit 1
fi

# Run SwiftLint on the Sources directory
./run_swiftlint.sh

# Check if SwiftLint found any errors (exit code 2 indicates errors were found)
if [ $? -eq 2 ]; then
  echo "SwiftLint found errors. Please fix them before committing."
  exit 1
fi

exit 0