platform :ios, '9.0'

target 'Tests' do
  use_frameworks!

  pod 'CrowdinSDK', :path => '../', :testspecs => ['Core_Tests', 'CrowdinProvider_Tests', 'CrowdinAPI_Tests', 'Login_Tests']

  target 'TestsTests' do
    inherit! :search_paths
  end

  target 'TestsUITests' do
    inherit! :search_paths
  end
end
